### ISSUE TITLE
Adapt library to the latest API changes

### ISSUE THREAD

**Issue by JoeZ99** [doofinder/pydoof#7]
https://github.com/peillis/helpapp/issues/2698

  - the delete datatype entrypoint has changed
  - indexing op with an unknown datatype is no longer allowed

**Comment by peillis** [comment]
you know nobody can see those links to helpapp right?

**Comment by JoeZ99** [comment]
I know, I use them just for references. People with such a distraction-prone mind as myself we need to constantly add remainders all over to keep ourselves from forgetting things.
